version: "3.9"

services:
  youtube-clone-backend-dev:
    container_name: youtube-clone-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8080"

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: youtube_clone_database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    